env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 8
  sourceType: module
plugins:
  - react
rules:
  react/jsx-filename-extension: 0
  no-unsafe-optional-chaining: 0
  no-nonoctal-decimal-escape: 0
  react/function-component-definition: 0
